version: '3.8'

services:
  #fdp-dashboard:
  #  image: ghcr.io/mdw-nl/fdp-dashboard:main
  #  container_name: fdp-dashboard
  #  ports:
  #    - "8080:8080"
  #  networks:
  #    - protrait

  api-server:
    image: ghcr.io/mdw-nl/api-protrait:main
    container_name: api-server
    ports:
      - "8000:8000"
    networks:
      - protrait

  dicomListener:
    image: ghcr.io/mdw-nl/dicom-listner:main
    depends_on:
      - postgres
    ports:
      - "104:104"
    environment:
      AE_TITLE: ${AE_TITLE}
    volumes:
      - /Users/alessioromita/Documents/setting_protrait_deploymant/config_list.yaml:/dicomsorter/Config/config.yaml

    networks:
      - protrait

  DVH-consumer:
    image: ghcr.io/mdw-nl/dvh_consumer:main
    depends_on:
        - dicomListener
    container_name: dvh-calculator
    volumes:
      - /Users/alessioromita/Documents/setting_protrait_deploymant/config_list.yaml:/DICOM_solver/DICOM_solver/Config/config.yaml
      - /Users/alessioromita/Documents/data_test_docker:/DICOM_solver/data 
    networks:
      - protrait
  #rdf-converter:
  #  image: ghcr.io/mdw-nl/rdf-converter:main
  #  container_name: rdf-converter
  #  networks:
  #    - protrait

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - protrait
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - protrait
  graphdb:
    image: ontotext/graphdb:10.6.4
    container_name: graphdb
    ports:
      - "7200:7200"
    volumes:
      - graphdb-data:/opt/graphdb/home
    networks:
      - protrait
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ connection
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - protrait
  fdp-dashboard:
    image: ghcr.io/mdw-nl/fdp-dashboard:main
    container_name: fdp-dashboard
    ports:
      - "8080:8080"
    networks:
      - protrait

volumes:
  graphdb-data:
  postgres-data:
  pgadmin-data:

networks:
  protrait: