version: '3.8'

services:
  fdp-dashboard:
    image: ghcr.io/mdw-nl/fdp-dashboard:main
    container_name: fdp-dashboard
    ports:
      - "8080:8080"
    networks:
      - protrait
  dicomsorter:
    build: .
    depends_on:
      - postgres
    ports:
      - "104:104"
    environment:
      AE_TITLE: ${AE_TITLE}
    networks:
      - protrait
  dvh-calculator:
    image: ghcr.io/mdw-nl/dvh-calculator:main
    container_name: dvh-calculator
    networks:
      - protrait
  rdf-converter:
    image: ghcr.io/mdw-nl/rdf-converter:main
    container_name: rdf-converter
    networks:
      - protrait
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - protrait
  graphdb:
    image: ontotext/graphdb:latest
    container_name: graphdb
    ports:
      - "7200:7200"
    volumes:
      - graphdb-data:/opt/graphdb/home
    networks:
      - protrait
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ connection
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - protrait

volumes:
  graphdb-data:
  postgres-data:

networks:
  protrait: