postgres:
    host: "postgres"
    port: "5432"
    username: "postgres"
    password: "postgres"
    db: "testdb"

rabbitMQ:
  host: "rabbitmq"
  port: "5672"
  username: "testuser"
  password: "testpassword"
  queue_name: "DICOM_Processor"

GraphDB:
    host: "graphdb"
    port: "7200"
    repo: "protrait"

API:
    host: "host.docker.internal"
    port: "8666"

dvh-calculations:
  -
    P-LUNG:
      roi: "Lung_L + Lung_R"
  -
    MeanDoseIpsiLateralParotidGland:
      roi: "Parotid_Ipsilateral"